const I = (x => x);
const K = (x => (y => x));
const R = (x => (y => y));
const S = (x => (y => (z => x(z)(y(z)))));
const W = (f => (x => f(x)(x)));
const C = (f => (x => (y => f(y)(x))));
const B = (f => (g => (x => f(g(x)))));
const F = (f => (g => (h => (x => f(g(x))(h(x))))));
const Unit = (x => x);
const True = (x => (y => x));
const False = (x => (y => y));
const cond = (c => (a => (b => c(a)(b))));
const not = (b => (x => (y => y)));
const and = (a => (b => a(b)((x => (y => y)))));
const or = (a => (b => a((x => (y => x)))(b)));
const Z = (fz => (fs => fz((x => x))));
const S = (n => (fz => (fs => fs(n))));
const inc = (n => (fz => (fs => fs(n))));
const dec = (n => n((fz => (fs => fz((x => x)))))((x => x)));
const main = (x => (fz => (fs => fz((x => x)))));
main();
